### ISSUE TITLE
Crash on killing creepers

### ISSUE THREAD

**Issue by Drock1994** [T145/elemental-creepers#1]
I am putting together a new pack and saw that you updated this mod and had to try it out, but I was using a Tinkers Construct Shuriken which if i'm not mistaken acts like an arrow.  Both times i tried to kill a Elemental Creeper the game crashed.

https://pastebin.com/wRMsj2UL
https://pastebin.com/Ms7m4S58

Here is my mod list:
https://pastebin.com/ZHfLSTJD

Thanks for updating the mod and I hope this helps

**Comment by T145** [comment]
This is interesting b/c I removed the casting in 0df20ffdad9ee439e53a180852a5c7be6b5837f3 to avoid this issue. After checking the event class methods, I found this:

```java
    /**
     * Retrieves the immediate causer of the damage, e.g. the arrow entity, not its shooter
     */
    @Nullable
    public Entity getImmediateSource()
    {
        return this.getTrueSource();
    }

    /**
     * Retrieves the true causer of the damage, e.g. the player who fired an arrow, the shulker who fired the bullet,
     * etc.
     */
    @Nullable
    public Entity getTrueSource()
    {
        return null;
    }
```

*Oh Forge...*

Should be resolved soon.
Thanks for the report!

**Comment by T145** [comment]
@Drock1994 See if v1.8 solves your issue!

**Comment by Drock1994** [comment]
It works much better....great job Thank You
