### ISSUE TITLE
Server Crash Still with Latest Version

### ISSUE THREAD

**Issue by Vyraal1** [T145/elemental-creepers#10]
https://hastebin.com/ihixavewul.sql

### Steps to Reproduce (including precondition)

Custom modpack - listed mods are in the description.

### Your Environment

- OS: Windows
- Minecraft version: 1.12.2
- Elemental Creepers version: v4.1.gf82c179  
- Forge version: 2623

**Comment by T145** [comment]
`at T145.elementalcreepers.core.ModLoader$ServerLoader.registerEntities(ModLoader.java:121)`
tells me it's a problem w/ the Friendly Creeper, and conviently it's the only creeper class where I use `@SideOnly(Side.CLIENT)` calls; deleting those should fix your issue!

**Comment by T145** [comment]
Now just build the mod and see if it works for you! Download the repo source, run `./gradlew.bat build`
and copy the jar file from the generated `releases` directory.
