### ISSUE TITLE
[1.14] Config doesn't seem to work properly

### ISSUE THREAD

**Issue by ghost** [T145/elemental-creepers#20]
Even when the spawn weight of a creeper is set to zero, it still spawns. reasonableSpawnRates does not exist either.

I am using the 1.14 version of the mod with the latest Fabric for 1.14.2. (Build 170 as of writing)

**Comment by T145** [comment]
May you enable `debug`, disable a creeper and give me the log output, as well as the disabled creeper?

**Comment by ghost** [comment]
There seems to be two files. One is config/T145.allthecreepers.toml and the other is config/T145/allthecreepers.toml... the one in the folder seems to still be at defaults. I'll try updating that one and see if the one in the subfolder is the one that the mod actually reads.

**Comment by T145** [comment]
In the latest version of the mod I moved it to the directory, so that should be your active config.
