### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by Insane-96** [T145/elemental-creepers#3]
I've read on Curseforge that you plan on renaming some creepers, I would like to translate the mod to Italian, but I need to know if I can translate now or have to wait for the "new names update"

**Comment by T145** [comment]
I plan on renaming Hydrogen to Ballistic and Electric to Lightning. You can translate just off that. There will also be config locale entries that I'll add in shortly. Just star the repo to stay up-to-date w/ my progress; I'll work on the locale stuff ASAP.

**Comment by Insane-96** [comment]
Base Italian translation (for creepers name only) has been created, now I'll wait for other strings to tranlate ^^

**Comment by T145** [comment]
You should be all set! Please use the en_us format as your template: https://github.com/T145/elemental-creepers/blob/master/src/main/resources/assets/elementalcreepers/lang/en_us.lang

**Comment by Insane-96** [comment]
Maybe radius here? https://github.com/T145/elemental-creepers/blob/master/src/main/resources/assets/elementalcreepers/lang/en_us.lang#L6

**Comment by T145** [comment]
Radii is the plural of radius; the category contains more than one radius, and you have the option of configuring more than one radius, hence "Radii" for the tooltip.
