### ISSUE TITLE
[BUG] Unable to view statistics

### ISSUE THREAD

**Issue by DzikiDzikers** [T145/elemental-creepers#6]
When I add Elemental Creepers to my mod pack and open my world I can't open my statistics, and only see this:
<p align="center"><img src="https://i.imgur.com/XEsBXbO.png"/></p>
Even after I load the game with only Elemental Creepers installed, I still can't open my statistics.

**Comment by T145** [comment]
Does it work w/ no mods installed? If so, could you post your game logs please?
