### ISSUE TITLE
texture glitches and friendly creeper height (Elemental Creepers Redux)

### ISSUE THREAD

**Issue by SharkPusherGDA** [T145/elemental-creepers#7]
### Expected Behavior

some normal textures and rendering

### Actual Behavior

illusion creeper has a hole at the right back of the head and back
earth creeper has green under the head in stead of brown
finally the friendly and spider creeper floats on nothing

### Steps to Reproduce

just normally spawn all 4 creepers

### Screenshot on This Problem

![glitch 1](https://user-images.githubusercontent.com/32912867/36890950-fdde90e6-1e53-11e8-8cb4-c61501172bd0.PNG)
![glitch 2](https://user-images.githubusercontent.com/32912867/36890964-05d10ee6-1e54-11e8-9571-c12e264edb27.PNG)
![glitch 3](https://user-images.githubusercontent.com/32912867/36890930-ef68fdf8-1e53-11e8-8cfc-c4808f4304fc.PNG)
![glitch 4](https://user-images.githubusercontent.com/32912867/36892756-e3f91074-1e59-11e8-902f-461de233938d.PNG)

### Your Environment

- Minecraft 1.12.2
- Forge 14.23.1.2555
- Elemental Creepers v3.8.3-g68a0adb

if you are reading this, i would like a response and if you accept the challenge of not i'd like to know why. this problem may be anticlimactic but i posted this issue because it's distracting and i'd love to see this mod evolve with your unique take

Sincerely SPGDA

**Comment by T145** [comment]
Good eye! The Earth and Illusion creeper issues are definitely texture related, which is not my forte. The textures are literally just recycled from the original mod. As for the Friendly and Spider creepers floating, that's an issue w/ their models, which I can fix. I'll add a tag for texture assistance and see if we can't find someone to help.

**Comment by T145** [comment]
Fixed the models: https://github.com/T145/elemental-creepers/commit/46fb9bd8405e9b5150714158bd9745effb8fa8aa

**Comment by SharkPusherGDA** [comment]
thank you very much T

**Comment by SharkPusherGDA** [comment]
how about i give it a go and try to fix the textures
just give the textures of illusion and earth creepers and try to patch it up
if not that's fine.

**Comment by T145** [comment]
Go for it!
- Earth Creeper: https://github.com/T145/elemental-creepers/blob/master/src/main/resources/assets/elementalcreepers/textures/entities/earthcreeper.png
- Illusion Creeper: https://github.com/T145/elemental-creepers/blob/76365dff90551857ecad00417dd6013798849660/src/main/resources/assets/elementalcreepers/textures/entities/illusioncreeper.png

**Comment by SharkPusherGDA** [comment]
![earthcreeper](https://user-images.githubusercontent.com/32912867/36928955-e8591ab2-1ede-11e8-941b-a0e69ff415ca.png)
![illusioncreeper](https://user-images.githubusercontent.com/32912867/36928956-ed79424c-1ede-11e8-9419-e45165fbf7ee.png)

yeah ok,.. it's just i'm terrible at coding

**Comment by T145** [comment]
Now just create a pull request! You just go to the "Pull Requests" tab and hit "Create New Pull Request" in the top right-hand corner. I like to give credit where it's due, and doing this will attribute the changes to you, not me.

**Comment by T145** [comment]
Actually since you made some other unnecessary changes to the repo I'll commit them to the repo but credit you for the changes. Thanks again!

**Comment by SharkPusherGDA** [comment]
no problem, those "unnecessary changes were just accidents
