### ISSUE TITLE
[1.12.2] Server Crash on Startup

### ISSUE THREAD

**Issue by Vyraal1** [T145/elemental-creepers#8]
### Expected Behavior

Not crashing

### Actual Behavior

Crashing

### Steps to Reproduce (including precondition)

https://hastebin.com/ubifiyolam.sql

### Your Environment

- OS: Windows
- Minecraft//Forge version: Forge 2623 on MC 1.12.2

**Comment by T145** [comment]
Try uninstalling Witchery and see if it boots from there. The root of that crashlog seems to indicate a conflict. I’ll investigate more on my end.

**Comment by Vyraal1** [comment]
I don't actually have Witchery installed, did you mean another mod?

**Comment by T145** [comment]
I meant Wizardy sorry. My brain is fried from midterms lol
The latest commit should fix the problem; Wizardy's asm injection get's upset when it's trying to load a client object and gets a serverside one.

**Comment by T145** [comment]
You're welcome 🌴 

[https://minecraft.curseforge.com/projects/elemental-creepers-redux/files/2539010](https://minecraft.curseforge.com/projects/elemental-creepers-redux/files/2539010)
